version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
  dependencies:
  override:
    - docker info
   steps:
        - run:
          name: Running tests
          command: echo test
