default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  sslmode: require
  host:  <%= ENV['DB_HOST'] %>
  user:  <%= ENV['DB_LOGIN'] %>
  password:  <%= ENV['DB_PASS'] %>
  
development:
  <<: *default
  database: rubyblog1

test:
  <<: *default
  database: <%= ENV['DB_DEPLOY'] %><%= ENV['CIRCLE_BUILD_NUM'] %>

production:
  <<: *default
  host:  195.69.187.166
  database:  railsblog
  user:  ruby
  password:  gor0shek
