
default: &default
  adapter: postgresql
  encoding: unicode
  host: 195.69.187.166
  user: ruby
  port: 5432
  password: gor0shek
  sslmode: require

development:
  <<: *default
  database: rubyblog

test:
  <<: *default
  database: db_name

production:
  <<: *default
  database: rubyblog
  username: ruby
  password: gor0shEk
