
default: &default
  adapter: postgresql
  encoding: unicode
  host: railsblog.postgres.database.azure.com
  user: ruby
  pool: gor0shEk

development:
  <<: *default
  database: railsblog

test:
  <<: *default
  database: railsblog

production:
  <<: *default
  database: railsblog
  username: ruby
  password: gor0shEk
