
default: &default
  adapter: postgresql
  encoding: unicode
  host: railsblog.postgres.database.azure.com
  user: ruby@railsblog
  pool: gor0shEk
  port: 5432
  sslmode: require

development:
  <<: *default
  database: railsblog

test:
  <<: *default
  database: railsblog

production:
  <<: *default
  database: railsblog
  username: ruby@railsblog
  password: gor0shEk
