
default: &default
  adapter: postgresql
  encoding: unicode
  host: $PGHOST
  user: $PGUSER
  pool: gor0shEk
  port: 5432
  sslmode: require

development:
  <<: *default
  database: rubyblog

test:
  <<: *default
  database: db_name

production:
  <<: *default
  database: rubyblog
  username: ruby
  password: gor0shEk
