
default: &default
  adapter: postgresql
  encoding: unicode
  host: 40.68.36.143
  user: ruby
  pool: gor0shEk
  port: 5432
  sslmode: require

development:
  <<: *default
  database: railsblog

test:
  <<: *default
  database: railsblog

production:
  <<: *default
  database: railsblog
  username: ruby
  password: gor0shEk
