default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  user: <%= ENV['DB_LOGIN'] %>
  port: 5432
  password: <%= ENV['DB_PASS'] %>
  sslmode: require

development:
  <<: *default
  database: rubyblog1

test:
  <<: *default
  database: <%= ENV['DB_DEPLOY'] %><%= ENV['CIRCLE_BUILD_NUM'] %>

production:
  <<: *default
  database: rubyblog

